# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_photo_editor.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(600, 370)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(600, 400))
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/source/246px-Adobe_Photoshop_CC_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("")
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setDockNestingEnabled(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setEnabled(True)
        self.widget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.widget.setMouseTracking(False)
        self.widget.setTabletTracking(False)
        self.widget.setToolTipDuration(-1)
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.horizontalLayout.addWidget(self.widget)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setStyleSheet("")
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout.addWidget(self.line_3)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setStyleSheet("")
        self.label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_1.setObjectName("label_1")
        self.gridLayout.addWidget(self.label_1, 0, 0, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setStyleSheet("")
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout.addWidget(self.line_5, 0, 1, 5, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setStyleSheet("")
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 2, 1, 1)
        self.eyes_slider = QtWidgets.QSlider(self.centralwidget)
        self.eyes_slider.setStyleSheet("")
        self.eyes_slider.setMaximum(100)
        self.eyes_slider.setSingleStep(1)
        self.eyes_slider.setProperty("value", 0)
        self.eyes_slider.setOrientation(QtCore.Qt.Horizontal)
        self.eyes_slider.setObjectName("eyes_slider")
        self.gridLayout.addWidget(self.eyes_slider, 0, 3, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setStyleSheet("")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 5, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setStyleSheet("")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setStyleSheet("")
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 2, 1, 1)
        self.nose_slider = QtWidgets.QSlider(self.centralwidget)
        self.nose_slider.setStyleSheet("")
        self.nose_slider.setMinimum(60)
        self.nose_slider.setMaximum(100)
        self.nose_slider.setPageStep(5)
        self.nose_slider.setProperty("value", 60)
        self.nose_slider.setOrientation(QtCore.Qt.Horizontal)
        self.nose_slider.setObjectName("nose_slider")
        self.gridLayout.addWidget(self.nose_slider, 1, 3, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setStyleSheet("")
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 5, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setStyleSheet("")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setStyleSheet("")
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 2, 2, 1, 1)
        self.face_slider = QtWidgets.QSlider(self.centralwidget)
        self.face_slider.setStyleSheet("")
        self.face_slider.setMinimum(60)
        self.face_slider.setMaximum(100)
        self.face_slider.setPageStep(5)
        self.face_slider.setOrientation(QtCore.Qt.Horizontal)
        self.face_slider.setObjectName("face_slider")
        self.gridLayout.addWidget(self.face_slider, 2, 3, 1, 2)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setStyleSheet("")
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 2, 5, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setStyleSheet("")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setStyleSheet("")
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 3, 2, 1, 1)
        self.lip_slider = QtWidgets.QSlider(self.centralwidget)
        self.lip_slider.setStyleSheet("")
        self.lip_slider.setMaximum(255)
        self.lip_slider.setOrientation(QtCore.Qt.Horizontal)
        self.lip_slider.setObjectName("lip_slider")
        self.gridLayout.addWidget(self.lip_slider, 3, 3, 1, 2)
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setStyleSheet("")
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 3, 5, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setStyleSheet("")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 4, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setStyleSheet("")
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 4, 2, 1, 1)
        self.mopi_slider = QtWidgets.QSlider(self.centralwidget)
        self.mopi_slider.setStyleSheet("")
        self.mopi_slider.setMinimum(0)
        self.mopi_slider.setMaximum(10)
        self.mopi_slider.setPageStep(1)
        self.mopi_slider.setOrientation(QtCore.Qt.Horizontal)
        self.mopi_slider.setObjectName("mopi_slider")
        self.gridLayout.addWidget(self.mopi_slider, 4, 3, 1, 2)
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setStyleSheet("")
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 4, 5, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(94, 13, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 5, 0, 1, 4)
        self.ok = QtWidgets.QPushButton(self.centralwidget)
        self.ok.setFocusPolicy(QtCore.Qt.TabFocus)
        self.ok.setStyleSheet("")
        self.ok.setAutoDefault(False)
        self.ok.setObjectName("ok")
        self.gridLayout.addWidget(self.ok, 5, 4, 1, 2)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.line_2.setAutoFillBackground(False)
        self.line_2.setStyleSheet("")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 6, 0, 1, 6)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setStyleSheet("")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 7, 0, 1, 1)
        self.rmacne_slider = QtWidgets.QSlider(self.centralwidget)
        self.rmacne_slider.setStyleSheet("")
        self.rmacne_slider.setMinimum(30)
        self.rmacne_slider.setMaximum(100)
        self.rmacne_slider.setOrientation(QtCore.Qt.Horizontal)
        self.rmacne_slider.setObjectName("rmacne_slider")
        self.gridLayout.addWidget(self.rmacne_slider, 7, 1, 1, 3)
        self.rmacne = QtWidgets.QPushButton(self.centralwidget)
        self.rmacne.setFocusPolicy(QtCore.Qt.TabFocus)
        self.rmacne.setStyleSheet("")
        self.rmacne.setObjectName("rmacne")
        self.gridLayout.addWidget(self.rmacne, 7, 4, 1, 2)
        self.gridLayout.setColumnStretch(3, 2)
        self.gridLayout.setColumnStretch(4, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(2, 3)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 28))
        self.menubar.setStyleSheet("")
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setTabletTracking(False)
        self.menuFile.setFocusPolicy(QtCore.Qt.TabFocus)
        self.menuFile.setAutoFillBackground(False)
        self.menuFile.setStyleSheet("")
        self.menuFile.setInputMethodHints(QtCore.Qt.ImhDate)
        self.menuFile.setTearOffEnabled(False)
        self.menuFile.setSeparatorsCollapsible(False)
        self.menuFile.setToolTipsVisible(False)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setFocusPolicy(QtCore.Qt.TabFocus)
        self.menuEdit.setStyleSheet("")
        self.menuEdit.setObjectName("menuEdit")
        self.menuFilter = QtWidgets.QMenu(self.menuEdit)
        self.menuFilter.setObjectName("menuFilter")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setFocusPolicy(QtCore.Qt.TabFocus)
        self.menuHelp.setStyleSheet("")
        self.menuHelp.setTearOffEnabled(False)
        self.menuHelp.setSeparatorsCollapsible(False)
        self.menuHelp.setToolTipsVisible(False)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setStyleSheet("")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/source/Picture Document.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon1)
        font = QtGui.QFont()
        self.actionOpen.setFont(font)
        self.actionOpen.setIconVisibleInMenu(True)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/source/Get Info Blue Button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon2)
        font = QtGui.QFont()
        self.actionAbout.setFont(font)
        self.actionAbout.setObjectName("actionAbout")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionResize = QtWidgets.QAction(MainWindow)
        self.actionResize.setObjectName("actionResize")
        self.actionBrightness = QtWidgets.QAction(MainWindow)
        self.actionBrightness.setObjectName("actionBrightness")
        self.actionContrast = QtWidgets.QAction(MainWindow)
        self.actionContrast.setObjectName("actionContrast")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/source/Export To Picture Document.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_as.setIcon(icon3)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtWidgets.QAction(MainWindow)
        self.actionRedo.setObjectName("actionRedo")
        self.actionBrightness_2 = QtWidgets.QAction(MainWindow)
        self.actionBrightness_2.setObjectName("actionBrightness_2")
        self.actionPhoto_size = QtWidgets.QAction(MainWindow)
        self.actionPhoto_size.setObjectName("actionPhoto_size")
        self.actionAdd = QtWidgets.QAction(MainWindow)
        self.actionAdd.setObjectName("actionAdd")
        self.actionBackground = QtWidgets.QAction(MainWindow)
        self.actionBackground.setObjectName("actionBackground")
        self.actionChartlet = QtWidgets.QAction(MainWindow)
        self.actionChartlet.setObjectName("actionChartlet")
        self.actionChangeFace = QtWidgets.QAction(MainWindow)
        self.actionChangeFace.setShortcut("")
        self.actionChangeFace.setObjectName("actionChangeFace")
        self.actionFilter0 = QtWidgets.QAction(MainWindow)
        self.actionFilter0.setObjectName("actionFilter0")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addAction(self.actionExit)
        self.menuFilter.addAction(self.actionFilter0)
        self.menuEdit.addAction(self.actionBackground)
        self.menuEdit.addAction(self.actionChartlet)
        self.menuEdit.addAction(self.menuFilter.menuAction())
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionChangeFace)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Photo Editor"))
        self.label_1.setText(_translate("MainWindow", "眼睛大小"))
        self.label_6.setText(_translate("MainWindow", "小"))
        self.label_5.setText(_translate("MainWindow", "大"))
        self.label_2.setText(_translate("MainWindow", "鼻子大小"))
        self.label_8.setText(_translate("MainWindow", "大"))
        self.label_7.setText(_translate("MainWindow", "小"))
        self.label_4.setText(_translate("MainWindow", "脸部大小"))
        self.label_10.setText(_translate("MainWindow", "大"))
        self.label_11.setText(_translate("MainWindow", "小"))
        self.label_3.setText(_translate("MainWindow", "嘴唇颜色"))
        self.label_12.setText(_translate("MainWindow", "红"))
        self.label_13.setText(_translate("MainWindow", "无"))
        self.label_14.setText(_translate("MainWindow", "磨皮程度"))
        self.label_15.setText(_translate("MainWindow", "粗"))
        self.label_16.setText(_translate("MainWindow", "细"))
        self.ok.setText(_translate("MainWindow", "确定"))
        self.label_9.setText(_translate("MainWindow", "半径"))
        self.rmacne.setText(_translate("MainWindow", "祛痘模式"))
        self.menuFile.setTitle(_translate("MainWindow", "文件(&F)"))
        self.menuEdit.setTitle(_translate("MainWindow", "编辑(&E)"))
        self.menuFilter.setTitle(_translate("MainWindow", "添加滤镜"))
        self.menuHelp.setTitle(_translate("MainWindow", "帮助(&H)"))
        self.actionOpen.setText(_translate("MainWindow", "&打开..."))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionExit.setText(_translate("MainWindow", "退出"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionAbout.setText(_translate("MainWindow", "&关于 Photo Editor"))
        self.actionAbout.setShortcut(_translate("MainWindow", "Ctrl+H"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionResize.setText(_translate("MainWindow", "Resize"))
        self.actionBrightness.setText(_translate("MainWindow", "Brightness"))
        self.actionContrast.setText(_translate("MainWindow", "Contrast"))
        self.actionSave_as.setText(_translate("MainWindow", "&另存为..."))
        self.actionSave_as.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionClose.setText(_translate("MainWindow", "关闭"))
        self.actionClose.setShortcut(_translate("MainWindow", "Ctrl+W"))
        self.actionSave.setText(_translate("MainWindow", "保存"))
        self.actionUndo.setText(_translate("MainWindow", "Undo"))
        self.actionRedo.setText(_translate("MainWindow", "Redo"))
        self.actionBrightness_2.setText(_translate("MainWindow", "Brightness"))
        self.actionPhoto_size.setText(_translate("MainWindow", "Photo size"))
        self.actionAdd.setText(_translate("MainWindow", "Add"))
        self.actionBackground.setText(_translate("MainWindow", "更换背景..."))
        self.actionBackground.setShortcut(_translate("MainWindow", "Ctrl+B"))
        self.actionChartlet.setText(_translate("MainWindow", "添加贴图..."))
        self.actionChartlet.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.actionChangeFace.setText(_translate("MainWindow", "换脸..."))
        self.actionFilter0.setText(_translate("MainWindow", "None"))
#import resource_rc
